service: cuchumbo-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  profile: cuchumbo-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SES:SendEmail
        - SES:SendRawEmail
        - SES:SendBulkTemplatedEmail
      Resource: "*"

functions:
  createCuchumbo:
    handler: handler.create
    description: Creates a randomized exchange based on the input cuchumbo object.
    memorySize: 512
    timeout: 20
    environment:
      SEED_SALT: ${file(../secrets.json):salt, 'default_salt'}
    events:
      - httpApi:
            method: POST
            path: /create

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.cuchumbo.io
    dev: dev-api.cuchumbo.io

  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true