service: cuchumbo-web

provider:
  name: aws
  region: us-east-1
  stage: dev
  profile: cuchumbo-dev

plugins:
  - serverless-finch

custom:
  client:
    bucketName: dev.cuchumbo.io
    distributionFolder: public
    